services:

  postgres:
    image: postgres:16

    container_name: document-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: document_intelligence

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: document-backend

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/chroma_db:/app/chroma_db

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend

    container_name: document-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: